export const PERSONAS = [
  {
    id: "deniz",
    name: "Deniz Aral",
    role: "CEO",
    department: "Strateji",
    initials: "DA",
    color: "#db783b",
    backstory:
      "İlk girişimi, müşteriye sormadan ürün geliştirdiği için kapandı. O deneyimden sonra büyük vaatlerden önce küçük kanıtlar aramayı öğrendi.",
    motivation: "Kanıta dayanan, ayakta kalabilen bir şirket kurmak.",
    fear: "Ekibin aylarca kimsenin istemediği bir ürün geliştirmesi.",
    traits: ["Meraklı", "Kararlı", "Özeleştirel"],
    skills: ["Strateji", "Müşteri keşfi", "Önceliklendirme"],
    preference: "validation",
    bias: 0.8,
  },
  {
    id: "ege",
    name: "Ege Tan",
    role: "CTO",
    department: "Teknoloji",
    initials: "ET",
    color: "#8379d4",
    backstory:
      "Bir önceki ekibinde aceleye getirilen bir sürüm önemli bir müşteriyi kaybettirdi. Artık basit ve ölçülebilir çözümleri savunuyor; bazen temkinli davranarak fırsatları kaçırıyor.",
    motivation: "İşe yarayan, anlaşılır ve güvenilir teknoloji üretmek.",
    fear: "Kontrol edilmemiş teknik varsayımların tüm ekibi zor durumda bırakması.",
    traits: ["Analitik", "Temkinli", "Yaratıcı"],
    skills: ["Prototipleme", "Veri modeli", "Sistem tasarımı"],
    preference: "technical",
    bias: 0.6,
  },
  {
    id: "selin",
    name: "Selin Acar",
    role: "CFO",
    department: "Finans",
    initials: "SA",
    color: "#77a87b",
    backstory:
      "Küçük aile işletmesinin nakit sıkıntısı yaşadığı bir dönemde sorumluluk aldı. Belirsiz getirileri hemen kabul etmiyor; sınırı belli deneylere alan açmayı öğreniyor.",
    motivation: "Şirkete yeni denemeler için zaman kazandırmak.",
    fear: "Gelir varsayımının gerçek nakitle karıştırılması.",
    traits: ["Titiz", "Gerçekçi", "Sabırlı"],
    skills: ["Bütçeleme", "Birim ekonomi", "Senaryo analizi"],
    preference: "economics",
    bias: -0.3,
  },
  {
    id: "mert",
    name: "Mert Yalın",
    role: "COO",
    department: "Operasyon",
    initials: "MY",
    color: "#d3ae60",
    backstory:
      "Eski işinde belirsiz görev dağılımı yüzünden üst üste teslim tarihleri kaçtı. Şimdi her karara bir sorumlu ve bitiş ölçütü ekliyor; kontrolü paylaşmak üzerinde çalışıyor.",
    motivation: "Fikirlerin bitmiş işe dönüşmesi.",
    fear: "Herkesin çalıştığı ama kimsenin teslim etmediği bir düzen.",
    traits: ["Düzenli", "Doğrudan", "Sorumlu"],
    skills: ["Operasyon", "Süreç tasarımı", "Kapasite planı"],
    preference: "execution",
    bias: 0.2,
  },
  {
    id: "ada",
    name: "Ada Keskin",
    role: "Ürün Lideri",
    department: "Ürün",
    initials: "AK",
    color: "#dc8794",
    backstory:
      "Çok emek verdiği bir ürünün kullanıcılarda karşılık bulmaması bakışını değiştirdi. Fikrine bağlanmadan önce sorunu anlamak istiyor, fakat bazen araştırmayı uzatıyor.",
    motivation: "Birinin iş gününü gerçekten kolaylaştıran ürünler yapmak.",
    fear: "Şık görünen ancak kullanılmayan özellikler.",
    traits: ["Empatik", "Sorgulayıcı", "Deneyci"],
    skills: ["Ürün keşfi", "Deney tasarımı", "Ölçüm"],
    preference: "validation",
    bias: 0.5,
  },
  {
    id: "can",
    name: "Can Bora",
    role: "Büyüme Lideri",
    department: "Büyüme",
    initials: "CB",
    color: "#69abb9",
    backstory:
      "Bir kampanyası yüksek tıklanma getirdiği halde hiç satış getirmedi. Artık görünürlük kadar dönüşümü de izliyor; hızlı denemeler için ekibi cesaretlendiriyor.",
    motivation: "Doğru müşteriye doğru değer önerisiyle ulaşmak.",
    fear: "Erişim sayılarının başarı sanılması.",
    traits: ["Girişken", "Hızlı", "İkna edici"],
    skills: ["Konumlandırma", "İçerik", "Büyüme deneyleri"],
    preference: "reach",
    bias: 1.1,
  },
  {
    id: "lale",
    name: "Lale Sönmez",
    role: "Tasarım Lideri",
    department: "Tasarım",
    initials: "LS",
    color: "#a58fbe",
    backstory:
      "Bir projede sade tasarımı gösterişsiz bulundu; sonrasında kullanılabilirlik çalışması yaklaşımını doğruladı. Kullanıcıyı savunuyor, eleştiri geldiğinde içine kapanmamaya çalışıyor.",
    motivation: "Karmaşık enerji kararlarını anlaşılır hale getirmek.",
    fear: "İnsanların anlamadığı bir arayüzü kullanmak zorunda kalması.",
    traits: ["Dikkatli", "Bağımsız", "Duyarlı"],
    skills: ["Arayüz", "Bilgi tasarımı", "Erişilebilirlik"],
    preference: "clarity",
    bias: 0.4,
  },
  {
    id: "baris",
    name: "Barış Erdem",
    role: "Araştırmacı",
    department: "Araştırma",
    initials: "BE",
    color: "#8f9caf",
    backstory:
      "Önceki projesinde yetersiz veriden çıkarılan güçlü bir iddia geri çekildi. Kaynak, varsayım ve gözlemi ayırıyor; belirsizlik varken de karar verebilmeyi öğreniyor.",
    motivation: "Ekibin doğru soruları sormasına yardımcı olmak.",
    fear: "Bir varsayımın doğrulanmış bilgi gibi yayılması.",
    traits: ["Şüpheci", "Özenli", "Açık fikirli"],
    skills: ["Pazar hipotezi", "Araştırma", "Eleştirel inceleme"],
    preference: "evidence",
    bias: -0.2,
  },
];

export const STRATEGIES = [
  {
    id: "office",
    title: "Ofislerde mesai dışı enerji kaybı",
    category: "office",
    segment: "20–150 çalışanlı ofisler",
    problem:
      "Boş saatlerde çalışan iklimlendirme ve aydınlatmanın fark edilmemesi",
    solution:
      "Haftalık tüketim çizelgesi, kapanış kontrol listesi ve bir tasarruf deneyi",
    hypothesis:
      "Yönetici, uygulanabilir bir kapanış planı için görüşme talep eder.",
    price: 2400,
    cost: 900,
    base: 0.64,
    validation: 9,
    technical: 6,
    economics: 8,
    execution: 9,
    reach: 8,
    clarity: 9,
    evidence: 7,
  },
  {
    id: "air",
    title: "KOBİ için basınçlı hava kaçak taraması",
    category: "air",
    segment: "Kompresör kullanan küçük üretim tesisleri",
    problem: "Ölçülmeyen kaçakların görünmez işletme gideri oluşturması",
    solution:
      "Ekipman envanteri ve vardiya dışı tüketim ölçümüne dayalı ön inceleme",
    hypothesis:
      "Bakım sorumlusu, ölçüm adımları net bir ön incelemeye ilgi gösterir.",
    price: 4200,
    cost: 1550,
    base: 0.52,
    validation: 7,
    technical: 9,
    economics: 9,
    execution: 6,
    reach: 6,
    clarity: 7,
    evidence: 8,
  },
  {
    id: "cold",
    title: "Soğuk zincirde kapı açılma günlüğü",
    category: "cold",
    segment: "Küçük gıda depoları ve marketler",
    problem:
      "Sık kapı açılmasının ve sıcaklık sapmalarının birlikte izlenmemesi",
    solution: "Kapı açılma kaydı, sıcaklık günlüğü ve operasyon deneyi taslağı",
    hypothesis:
      "Depo yöneticisi, mevcut kayıtlarla başlayabilen bir pilotu inceler.",
    price: 3600,
    cost: 1350,
    base: 0.48,
    validation: 8,
    technical: 8,
    economics: 7,
    execution: 7,
    reach: 7,
    clarity: 8,
    evidence: 9,
  },
  {
    id: "solar",
    title: "Çatı GES için performans kaybı günlüğü",
    category: "solar",
    segment: "Çatı güneş santrali bulunan küçük işletmeler",
    problem: "Beklenen ve ölçülen üretim farkının düzenli incelenmemesi",
    solution:
      "Üretim kaydı şablonu, gölgelenme gözlem formu ve bakım kontrol planı",
    hypothesis:
      "Tesis sorumlusu, üretim sapmasını anlaşılır gösteren bir rapor için pilot ister.",
    price: 4800,
    cost: 1900,
    base: 0.43,
    validation: 7,
    technical: 9,
    economics: 8,
    execution: 6,
    reach: 6,
    clarity: 8,
    evidence: 9,
  },
  {
    id: "school",
    title: "Okul binalarında tüketim farkındalığı",
    category: "school",
    segment: "Özel okul ve eğitim merkezi yöneticileri",
    problem:
      "Sınıflar ve tatil günleri için ortak bir enerji takip alışkanlığının olmaması",
    solution:
      "Haftalık sayaç tablosu, görev kartları ve bina kapanış protokolü",
    hypothesis:
      "Okul yönetimi, donanım yatırımı gerektirmeyen bir takip setini değerlendirir.",
    price: 1800,
    cost: 700,
    base: 0.58,
    validation: 9,
    technical: 5,
    economics: 6,
    execution: 9,
    reach: 9,
    clarity: 9,
    evidence: 7,
  },
  {
    id: "heat",
    title: "Küçük tesisler için atık ısı fırsat haritası",
    category: "heat",
    segment: "Fırın, kurutma veya sıcak proses kullanan KOBİler",
    problem:
      "Isı kaynakları ile olası kullanım alanlarının birlikte haritalanmaması",
    solution:
      "Sıcaklık ve çalışma saati envanteriyle mühendis incelemesine hazırlık dosyası",
    hypothesis:
      "İşletme sahibi, yatırım kararı vermeden bir fırsat envanteri hazırlamaya açıktır.",
    price: 5600,
    cost: 2400,
    base: 0.36,
    validation: 6,
    technical: 9,
    economics: 8,
    execution: 4,
    reach: 5,
    clarity: 6,
    evidence: 9,
  },
];
